# Generated by Django 3.2.15 on 2022-10-01 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=45)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('dentist', models.CharField(choices=[('first_dentist', 'Dr. Becket'), ('second_dentist', 'Dr. Giku')], default='first_dentist', max_length=25)),
                ('service', models.CharField(choices=[('consultation', 'Consultation'), ('bridges', 'Bridges'), ('crowns', 'Crowns'), ('fillings', 'Fillings'), ('canal', 'Root canal treatment'), ('scale', 'Scale and polish'), ('braces', 'Braces'), ('wisdom', 'Wisdom tooth removal'), ('implants', 'Dental implants'), ('dentures', 'Dentures or false teeth'), ('whitening', 'Teeth whitening'), ('veneers', 'Dental veneers')], default='consultation', max_length=25)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
    ]
